#!/usr/bin/env bash

ROOT=$(git rev-parse --show-toplevel)
GODOT_VERSION="4.3-stable"
GDUNIT_VERSION="4.5.0"
GODOT_BIN="$ROOT/.bin/godot"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    platform="linux_x86_64"
    spec="linux.x86_64"
    extension=""
elif [[ $OSTYPE == "msys" ]]; then
    platform="win64"
    spec="win64.exe"
    extension=".exe"
else
    echo "Unsupported platform"
    exit 1
fi

dir=$(mktemp -d)
zip="$dir/godot.zip"

curl -o "$zip" -L "https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_mono_${platform}.zip" 
unzip -d "$ROOT/.bin/" "$zip" 
cat << EOF > "$ROOT/.bin/godot"
#!/usr/bin/env bash

cd "$ROOT/.bin"
exec "$ROOT/.bin/Godot_v${GODOT_VERSION}_mono_${platform}/Godot_v${GODOT_VERSION}_mono_${spec}"
EOF

zip="$dir/gdunit.zip"
curl -o "$zip" -L "https://github.com/MikeSchulze/gdUnit4/archive/refs/tags/v${GDUNIT_VERSION}.zip"
unzip "%zip" -d "$dir/gdunit"
mkdir "$ROOT/addons"
move "$dir/gdunit/gdUnit4-${GDUNIT_VERSION}/addons/gdUnit4" "$ROOT/addons/gdUnit4"

# Generate test adapter
dotnet test
